### ISSUE TITLE
embed-resources results in bug

### ISSUE THREAD

**Issue by Ifitrains** [shafayetShafee/reveal-header#20]
Hi, 

if you use embed-resources: true, the logo behaves very irrationally: 

```
---
format:
  revealjs:
    slide-number: true
    footer: <https://quarto.org>
    header: Quarto Presentations with beautiful slide decks made by RevealJs
    header-logo: images/Vector-based_example.svg
    embed-resources: true
filters:
  - reveal-header
---
```

![image](https://github.com/shafayetShafee/reveal-header/assets/43036806/ed9866e8-a8d7-4e1a-ac94-4734a72634b2)
