### ISSUE TITLE
`subtitle-as-header: true` breaks render

### ISSUE THREAD

**Issue by dtinhvo** [shafayetShafee/reveal-header#23]
I am having issue with turning on the `subtitle-as-header:` option, as when it is true quarto render errors out with this stacktrace:

```
Error running filter /opt/quarto/share/filters/main.lua:
Inline, list of Inlines, or string expected, got nil
        while retrieving function argument content
        while retrieving arguments for function Para
stack traceback:
        ...xtensions/shafayetShafee/reveal-header/reveal-header.lua:105: in function <...xtensions/shafayetShafee/reveal-header/reveal-header.lua:67>
        [C]: in ?
        [C]: in method 'walk'
        /opt/quarto/share/filters/main.lua:557: in local 'checked_walk'
        /opt/quarto/share/filters/main.lua:609: in function 'run_emulated_filter'
        /opt/quarto/share/filters/main.lua:1334: in local 'callback'
        [string "..."]:1888: in field 'withScriptFile'
        /opt/quarto/share/filters/main.lua:1350: in upvalue 'run_emulated_filter_chain'
        /opt/quarto/share/filters/main.lua:1388: in function </opt/quarto/share/filters/main.lua:1385>
stack traceback:
        /opt/quarto/share/filters/main.lua:557: in local 'checked_walk'
        /opt/quarto/share/filters/main.lua:609: in function 'run_emulated_filter'
        /opt/quarto/share/filters/main.lua:1334: in local 'callback'
        [string "..."]:1888: in field 'withScriptFile'
        /opt/quarto/share/filters/main.lua:1350: in upvalue 'run_emulated_filter_chain'
        /opt/quarto/share/filters/main.lua:1388: in function </opt/quarto/share/filters/main.lua:1385>
```

Reproducible example: 
```

---
title: "Documentation"
# subtitle: "Create beautiful interactive slide decks with Reveal.js"
date: last-modified
date-format: "DD MMM, YYYY"
format: 
    revealjs:
        slide-number: true
        preview-links: true
        progress: true
        sc-sb-title: true
        subtitle-as-header: true
filters: 
  - reveal-header
slide-level: 3
number-sections: true
embed-resources: true

footer: "Footer TBD"

---

# Section

## Incremental slides
```
I am rendering with `quarto preview ${file.qmd} --watch-inputs --port 7777`, and `quarto render` also breaks similarly. I did not install 'knitr' because I don't want to introduce a dependency that I will not use.
