### ISSUE TITLE
Section does not change if the section does not contain a subsection

### ISSUE THREAD

**Issue by tomasrei** [shafayetShafee/reveal-header#24]
I believe this is a bug that happens if a section does not contain a subsection. 

I used your example and added two new sections at the end. Try it and notice what happens on the last slide. It shows Section 2 where it should say "Section 3" (at least I think it should!).

Hopefully, this makes sense.

Thanks!

```
---
title: "Quarto Presentations"
subtitle: "Create beautiful interactive slide decks with Reveal.js"
author: Shafayet Khan Shafee
date: last-modified
date-format: "DD MMM, YYYY"
format: 
  revealjs:
    slide-number: true
    sc-sb-title: true
filters: 
  - reveal-header
slide-level: 3
number-sections: true
engine: knitr
embed-resources: true
---

# Section 

## Subsection

### TODO

- Turn off alarm
- Get out of bed

### TODO

- Get freshed
- Make the beds

## Subsection

### TODO

- Eat eggs
- Drink coffee

### TODO

- Walk a bit
- More ...


# Section {background="#43464B"}

## Subsection {background="#43464B"}

### TODO {background="#43464B"}

- Turn off alarm
- Get out of bed

### TODO {background="#43464B"}

- Get freshed
- Make the beds


## Subsection {background="#43464B"}

### TODO {background="#43464B"}

- Eat eggs
- Drink coffee

### TODO {background="#43464B"}

- Walk a bit
- More ...

# Section {background="#41464B"}

New section 1

# Section {background="#43564B"}

New section 2. Shouldn't "Section 3" and not "Section 2" be in the top left corner on this slide?
```
